name: Autorest Testserver CI
trigger: none
pr:
  - main

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: main
    displayName: "Build and test"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - script: |
          npm install -g npm
          npm install
        displayName: "Install dependencies"

      - script: |
          npm run build
        displayName: "Build"

      - script: npm run test:ci
        displayName: Test

      - script: npm run lint
        displayName: Lint

      - script: npm run check-format
        displayName: Check formatting

      - script: |
          npm link
          autorest-testserver validate-spec-coverage
        displayName: Validate OpenAPI specs mock API coverage
        continueOnError: true
